/* CampusLock - SQLite/Express version. The UI remains the same; data is loaded through the backend API. */
const API='/api';
const ADMIN_USER='admin', ADMIN_PASS='admin123';
const app=document.getElementById('app'); let currentStudentId=sessionStorage.getItem('campuslock_student')||null; let isAdmin=sessionStorage.getItem('campuslock_admin')==='true'; let toastTimer;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const today=()=>new Date().toISOString().slice(0,10); const dateObj=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}; const iso=d=>d.toISOString().slice(0,10); const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const fmt=s=>s?dateObj(s).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'-';
const daysRemaining=e=>Math.max(0,Math.ceil((dateObj(e)-new Date(new Date().setHours(0,0,0,0)))/86400000));
const priority=d=>{d=Number(d);if(d>=30)return'VERY HIGH';if(d>=15)return'HIGH';if(d>=5)return'MEDIUM';return'LOW'}; const priorityRank=p=>p==='VERY HIGH'?4:p==='HIGH'?3:p==='MEDIUM'?2:1;
async function api(url,options={}){const r=await fetch(API+url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||'Request failed');return data}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
function btn(text,cls,onclick){return `<button class="btn ${cls}" onclick="${onclick}">${text}</button>`} function layout(title,content,actions=''){app.innerHTML=`<header class="topbar"><div><div class="brand">🔒 CampusLock</div><div class="subtitle">${esc(title)}</div></div><div class="nav-actions">${actions}</div></header>${content}`}
function goHome(){currentStudentId=null;isAdmin=false;sessionStorage.clear();renderHome()}
function renderHome(){app.innerHTML=`<div class="center"><div class="hero-card"><div style="font-size:52px">🔒</div><h1>CampusLock</h1><p>College Locker Management System</p><p>Reserve a locker based on your need, choose exactly how many days you require it, and track your expiry date.</p><div class="hero-buttons">${btn('🔐 Student Login','primary','renderStudentLogin()')} ${btn('👤 Create Student Account','success','renderRegister()')} ${btn('👨‍💼 Admin Login','dark','renderAdminLogin()')}</div><div class="notice" style="margin-top:20px">Storage: SQLite3 database • Node.js + Express backend</div><div class="footer">CampusLock Mini Project</div></div></div>`}
function renderRegister(){layout('Student Registration',`<main class="container"><div class="form-card card"><h2>Create Student Account</h2><p class="hint">All fields marked * are required.</p><form onsubmit="registerStudent(event)"><div class="form-grid"><div class="field"><label>Student ID *</label><input id="rId" required></div><div class="field"><label>Full Name *</label><input id="rName" required></div><div class="field"><label>Email *</label><input id="rEmail" type="email" required></div><div class="field"><label>Password *</label><input id="rPass" type="password" required></div><div class="field full-field"><label>Home Address</label><input id="rAddress"></div><div class="field"><label>Distance to College (km) *</label><input id="rDistance" type="number" min="0" step="0.1" required oninput="updatePriorityHint()"></div><div class="field"><label>Calculated Priority</label><input id="rPriority" readonly placeholder="Enter distance"></div></div><div class="notice">Priority: ≥30 km = VERY HIGH • 15–29.9 km = HIGH • 5–14.9 km = MEDIUM • &lt;5 km = LOW</div><div class="form-actions">${btn('Create Account','success','this.closest(\'form\').requestSubmit()')} ${btn('Back','light','renderHome()')}</div></form></div></main>`)}
function updatePriorityHint(){const d=document.getElementById('rDistance')?.value;const p=document.getElementById('rPriority');if(p)p.value=d===''?'':priority(d)}
async function registerStudent(e){e.preventDefault();try{const d=Number(rDistance.value);const x=await api('/register',{method:'POST',body:JSON.stringify({studentId:rId.value.trim(),name:rName.value.trim(),email:rEmail.value.trim(),password:rPass.value,address:rAddress.value.trim(),distance:d})});toast('Registration successful');renderStudentLogin()}catch(e){toast(e.message)}}
function renderStudentLogin(){layout('Student Login',`<main class="container"><div class="form-card card"><h2>🔐 Student Login</h2><form onsubmit="studentLogin(event)"><div class="field"><label>Student ID</label><input id="sId" required></div><div class="field" style="margin-top:14px"><label>Password</label><input id="sPass" type="password" required></div><div class="form-actions">${btn('Login','primary','this.closest(\'form\').requestSubmit()')} ${btn('Register','success','renderRegister()')} ${btn('Home','light','renderHome()')}</div></form></div></main>`)}
async function studentLogin(e){e.preventDefault();try{const x=await api('/login',{method:'POST',body:JSON.stringify({studentId:sId.value.trim(),password:sPass.value})});currentStudentId=x.student.studentId;sessionStorage.setItem('campuslock_student',currentStudentId);renderStudentDashboard()}catch(e){toast(e.message)}}
function renderAdminLogin(){layout('Admin Login',`<main class="container"><div class="form-card card"><h2>👨‍💼 Admin Login</h2><form onsubmit="adminLogin(event)"><div class="field"><label>Username</label><input id="aUser" required></div><div class="field" style="margin-top:14px"><label>Password</label><input id="aPass" type="password" required></div><div class="notice">Demo credentials: <b>admin</b> / <b>admin123</b></div><div class="form-actions">${btn('Login','dark','this.closest(\'form\').requestSubmit()')} ${btn('Home','light','renderHome()')}</div></form></div></main>`)}
async function adminLogin(e){e.preventDefault();try{await api('/admin/login',{method:'POST',body:JSON.stringify({username:aUser.value,password:aPass.value})});isAdmin=true;sessionStorage.setItem('campuslock_admin','true');renderAdminDashboard('lockers')}catch(e){toast(e.message)}}
async function renderStudentDashboard(){try{const x=await api('/students/'+encodeURIComponent(currentStudentId)+'/dashboard');const s=x.student,b=x.booking;const av=await api('/students/'+encodeURIComponent(currentStudentId)+'/available-lockers');layout('Student Dashboard',`<main class="container"><div class="dashboard-head"><div><h1>Welcome, ${esc(s.name)}</h1><p>Student ID: ${esc(s.studentId)}</p></div><div>${btn('Logout','dark','goHome()')}</div></div><div class="stats"><div class="stat"><div class="label">Priority</div><div class="value">${esc(s.priority)}</div></div><div class="stat"><div class="label">Distance</div><div class="value">${Number(s.distance).toFixed(1)} km</div></div><div class="stat"><div class="label">Total Lockers</div><div class="value">${av.lockers.length+(b?1:0)}</div></div><div class="stat"><div class="label">Available</div><div class="value">${av.lockers.length}</div></div></div><div class="grid-2"><section class="card ${b?'booking-active':''}"><h2>🔒 My Locker</h2>${b?bookingCard(s,b):`<div class="empty"><div style="font-size:40px">🔓</div><p>You don't have an active locker.</p>${btn('Book a Locker','success','renderBooking()')}</div>`}</section><section class="card"><h2>Available Lockers</h2>${lockerTable(av.lockers)}</section></div></main>`)}catch(e){toast(e.message);if(e.message==='Student not found')goHome()}}
function bookingCard(s,b){const duration=Math.max(0,Math.round((dateObj(b.expiryDate)-dateObj(b.startDate))/86400000));return `<div class="big">${esc(b.lockerNumber)}</div><div class="detail-grid"><div class="detail"><b>Block / Size</b>${esc(b.block)} / ${esc(b.size)}</div><div class="detail"><b>Duration</b>${duration} days</div><div class="detail"><b>Start Date</b>${fmt(b.startDate)}</div><div class="detail"><b>Expiry Date</b>${fmt(b.expiryDate)}</div><div class="detail"><b>Days Remaining</b>${daysRemaining(b.expiryDate)} days</div><div class="detail"><b>Status</b><span class="badge green">ACTIVE</span></div></div><div class="form-actions">${btn('Cancel Locker','danger',`cancelBooking('${esc(s.studentId)}')`)}</div>`}
function lockerTable(rows){return `<div class="table-wrap"><table class="table"><thead><tr><th>Locker</th><th>Block</th><th>Size</th><th>Status</th></tr></thead><tbody>${rows.map(l=>`<tr><td><b>${esc(l.number)}</b></td><td>${esc(l.block)}</td><td>${esc(l.size)}</td><td><span class="badge green">AVAILABLE</span></td></tr>`).join('')||`<tr><td colspan="4" class="empty">No lockers available</td></tr>`}</tbody></table></div>`}
async function renderBooking(){try{const x=await api('/students/'+encodeURIComponent(currentStudentId)+'/available-lockers');const av=x.lockers;if(!av.length){toast('No lockers are currently available');return renderStudentDashboard()}const d=await api('/students/'+encodeURIComponent(currentStudentId)+'/dashboard');const s=d.student;layout('Book a Locker',`<main class="container"><div class="form-card card"><h2>🔒 Reserve Your Locker</h2><div class="notice">Choose the locker and tell us exactly how many days you need it.</div><form onsubmit="confirmBooking(event)"><div class="field"><label>Locker *</label><select id="bLocker" required>${av.map(l=>`<option value="${l.id}">${esc(l.number)} • Block ${esc(l.block)} • ${esc(l.size)}</option>`).join('')}</select></div><div class="field" style="margin-top:14px"><label>Number of Days Required *</label><input id="bDays" type="number" min="1" max="3650" value="30" required oninput="previewBooking()"></div><div class="detail-grid"><div class="detail"><b>Start Date</b><span id="bStart">${fmt(today())}</span></div><div class="detail"><b>Expiry Date</b><span id="bExpiry">${fmt(iso(addDays(new Date(),30)))}</span></div><div class="detail"><b>Days Remaining</b><span id="bRemain">30 days</span></div><div class="detail"><b>Your Priority</b>${esc(s.priority)}</div></div><div class="warning notice">The locker will be released automatically after the expiry date.</div><div class="form-actions">${btn('Confirm Booking','success','this.closest(\'form\').requestSubmit()')} ${btn('Back','light','renderStudentDashboard()')}</div></form></div></main>`)}catch(e){toast(e.message)}}
function previewBooking(){const n=Number(document.getElementById('bDays')?.value||0);const exp=document.getElementById('bExpiry'),rem=document.getElementById('bRemain');if(n>=1&&n<=3650){exp.textContent=fmt(iso(addDays(new Date(),n)));rem.textContent=n+' days'}else{exp.textContent='-';rem.textContent='Invalid duration'}}
async function confirmBooking(e){e.preventDefault();try{await api('/bookings',{method:'POST',body:JSON.stringify({studentId:currentStudentId,lockerId:Number(bLocker.value),days:Number(bDays.value)})});toast('Locker booked successfully');renderStudentDashboard()}catch(e){toast(e.message);if(e.message.includes('no longer'))renderBooking()}}
async function cancelBooking(id){if(!confirm('Cancel this locker booking? The locker will become available immediately.'))return;try{await api('/bookings/student/'+encodeURIComponent(id),{method:'DELETE'});toast('Locker released');renderStudentDashboard()}catch(e){toast(e.message)}}
async function renderAdminDashboard(tab='lockers'){if(!isAdmin)return renderAdminLogin();try{const x=await api('/admin/data');const available=x.lockers.filter(l=>!l.bookingId).length;layout('Admin Dashboard',`<main class="container"><div class="dashboard-head"><div><h1>👨‍💼 Admin Dashboard</h1><p>Manage lockers, bookings and student priority.</p></div>${btn('Logout','dark','goHome()')}</div><div class="stats"><div class="stat"><div class="label">Total Lockers</div><div class="value">${x.lockers.length}</div></div><div class="stat"><div class="label">Available</div><div class="value">${available}</div></div><div class="stat"><div class="label">Active Bookings</div><div class="value">${x.bookings.length}</div></div><div class="stat"><div class="label">Students</div><div class="value">${x.students.length}</div></div></div><div class="card"><div class="tabs"><button class="tab ${tab==='lockers'?'active':''}" onclick="renderAdminDashboard('lockers')">🔒 Lockers</button><button class="tab ${tab==='bookings'?'active':''}" onclick="renderAdminDashboard('bookings')">📅 Bookings</button><button class="tab ${tab==='students'?'active':''}" onclick="renderAdminDashboard('students')">🏆 Student Priority</button></div><div id="adminTab">${tab==='lockers'?adminLockers(x.lockers):tab==='bookings'?adminBookings(x.bookings):adminStudents(x.students)}</div></div></main>`)}catch(e){toast(e.message)}}
function adminLockers(rows){return `<div class="form-actions" style="margin-top:0;margin-bottom:12px">${btn('+ Add Locker','success','addLocker()')} ${btn('Refresh','primary',"renderAdminDashboard('lockers')")}</div><div class="table-wrap"><table class="table"><thead><tr><th>Locker</th><th>Block</th><th>Size</th><th>Status</th><th>Student</th><th>Expiry</th><th>Action</th></tr></thead><tbody>${rows.map(l=>`<tr><td><b>${esc(l.number)}</b></td><td>${esc(l.block)}</td><td>${esc(l.size)}</td><td>${l.bookingId?'<span class="badge red">BOOKED</span>':'<span class="badge green">AVAILABLE</span>'}</td><td>${l.studentName?esc(l.studentName):'-'}</td><td>${l.expiryDate?fmt(l.expiryDate):'-'}</td><td>${l.bookingId?'<span class="hint">Locked</span>':btn('Delete','danger small',`deleteLocker(${l.id},'${esc(l.number)}')`)}</td></tr>`).join('')||`<tr><td colspan="7" class="empty">No lockers</td></tr>`}</tbody></table></div>`}
async function addLocker(){const number=prompt('Locker Number (e.g. L-301):');if(!number)return;const block=prompt('Block:','C');if(block===null)return;const size=prompt('Size: Small, Medium or Large','Medium');if(size===null)return;try{await api('/admin/lockers',{method:'POST',body:JSON.stringify({number,block,size})});toast('Locker added');renderAdminDashboard('lockers')}catch(e){toast(e.message)}}
async function deleteLocker(id,num){if(confirm('Delete locker '+num+'?'))try{await api('/admin/lockers/'+id,{method:'DELETE'});toast('Locker deleted');renderAdminDashboard('lockers')}catch(e){toast(e.message)}}
function adminBookings(rows){return `<div class="notice">Expired bookings are automatically removed by the server.</div><div class="table-wrap"><table class="table"><thead><tr><th>Student ID</th><th>Student</th><th>Locker</th><th>Start</th><th>Duration</th><th>Expiry</th><th>Remaining</th></tr></thead><tbody>${rows.map(b=>{const duration=Math.max(0,Math.round((dateObj(b.expiryDate)-dateObj(b.startDate))/86400000));return `<tr><td>${esc(b.studentId)}</td><td>${esc(b.name)}</td><td><b>${esc(b.lockerNumber)}</b></td><td>${fmt(b.startDate)}</td><td>${duration} days</td><td>${fmt(b.expiryDate)}</td><td>${daysRemaining(b.expiryDate)} days</td></tr>`}).join('')||`<tr><td colspan="7" class="empty">No active bookings</td></tr>`}</tbody></table></div>`}
function adminStudents(rows){return `<div class="table-wrap"><table class="table"><thead><tr><th>Rank</th><th>Student ID</th><th>Name</th><th>Distance</th><th>Priority</th><th>Locker</th></tr></thead><tbody>${rows.map((s,i)=>`<tr><td><b>${i+1}</b></td><td>${esc(s.studentId)}</td><td>${esc(s.name)}</td><td>${Number(s.distance).toFixed(1)} km</td><td><span class="badge ${s.priority==='VERY HIGH'?'red':s.priority==='HIGH'?'orange':'blue'}">${esc(s.priority)}</span></td><td>${s.lockerNumber?esc(s.lockerNumber):'Not Assigned'}</td></tr>`).join('')||`<tr><td colspan="6" class="empty">No students registered</td></tr>`}</tbody></table></div>`}
renderHome();
